server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: zuul-service
zuul:
  routes:
    api-service-routing:
      path: /api/**
      serviceId: api-service
    webclient-service-routing:
      path: /**
      serviceId: webclient-service
  ignored-patterns:
    - /login**
    - /logout**
security:
  oauth2:
    client:
      client-id: oauthClientId
      client-secret: oauthClientSecret
      accessTokenUri: http://localhost:9090/oauth/token
      userAuthorizationUri: http://localhost:9090/oauth/authorize
    resource:
      jwt:
        key-value: IT_SHOULD_BE_KEYPAIR